function changeTheme() {
    const checkbox = document.getElementById("day-night-checkbox-id")
    let root = document.documentElement.style
    if (checkbox.checked) {
        root.setProperty("--color0", "#00a1b0")
        root.setProperty("--color1", "#01606c")
        root.setProperty("--color2", "#00f4ff")
        root.setProperty("--color3", "#00a7ab")
        root.setProperty("--color4", "#1e838a")
        root.setProperty("--background0", "#3d3d42")
        root.setProperty("--background1", "#4b5760")
        root.setProperty("--background2", "#343e4f")
        root.setProperty("--background3", "#959daf")
        root.setProperty("--background4", "#dedede")
        root.setProperty("--border-color", "#ffffff")
        root.setProperty("--background-color", "#0c1017")
        root.setProperty("--background-box-title", "#424242")
        root.setProperty("--gradient-color", "#2b2f34")
        root.setProperty("--text-color", "#ffffff")
        root.setProperty("--notification-color-success", "#156532")
        root.setProperty("--notification-color-success-border", "#3fd778")
        root.setProperty("--notification-color-fail", "#913030")
        root.setProperty("--notification-color-fail-border", "#f66262")
    } else {
        root.setProperty("--color0", "#ccfcff")
        root.setProperty("--color1", "#b2f9fd")
        root.setProperty("--color2", "#009ba2")
        root.setProperty("--color3", "#25c6ce")
        root.setProperty("--color4", "#20b6be")
        root.setProperty("--background0", "#e1e1e1")
        root.setProperty("--background1", "#b5bdc4")
        root.setProperty("--background2", "#62738c")
        root.setProperty("--background3", "#303744")
        root.setProperty("--background4", "#282828")
        root.setProperty("--border-color", "#000000")
        root.setProperty("--background-color", "#ffffff")
        root.setProperty("--background-box-title", "#d0d0d0")
        root.setProperty("--gradient-color", "#aebcd2")
        root.setProperty("--text-color", "#000000")
        root.setProperty("--notification-color-success", "#3fd778")
        root.setProperty("--notification-color-success-border", "#156532")
        root.setProperty("--notification-color-fail", "#f66262")
        root.setProperty("--notification-color-fail-border", "#913030")
    }
}
