function changeTheme() {
    is_dark_theme = !is_dark_theme
    changeDigitsColorOnConnections()
    const checkbox = document.getElementById("day-night-checkbox-id")
    let root = document.documentElement.style
    if (checkbox.checked) {
        root.setProperty("--color0", "#00a1b0")
        root.setProperty("--color0-model-success-connection", "#17b000")
        root.setProperty("--color0-model-error-connection", "#b01500")
        root.setProperty("--color1", "#01606c")
        root.setProperty("--color2", "#00f4ff")
        root.setProperty("--color2-model-success-connection", "#5eff00")
        root.setProperty("--color2-model-error-connection", "#ff1e00")
        root.setProperty("--color3", "#00a7ab")
        root.setProperty("--color3-model-success-connection", "#25ab00")
        root.setProperty("--color3-model-error-connection", "#ab0600")
        root.setProperty("--color4", "#1e838a")
        root.setProperty("--color4-model-success-node", "#468a1e")
        root.setProperty("--color4-model-error-node", "#8a2b1e")
        root.setProperty("--background0", "#3d3d42")
        root.setProperty("--background1", "#4b5760")
        root.setProperty("--background2", "#343e4f")
        root.setProperty("--background3", "#959daf")
        root.setProperty("--background4", "#dedede")
        root.setProperty("--border-color", "#ffffff")
        root.setProperty("--background-color", "#0c1017")
        root.setProperty("--background-box-title", "#424242")
        root.setProperty("--gradient-color", "#2b2f34")
        root.setProperty("--text-color", "#ffffff")
        root.setProperty("--notification-color-success", "#156532")
        root.setProperty("--notification-color-success-border", "#3fd778")
        root.setProperty("--notification-color-fail", "#913030")
        root.setProperty("--notification-color-fail-border", "#f66262")
    } else {
        root.setProperty("--color0", "#ccfcff")
        root.setProperty("--color0-model-success-connection", "#e6ffcc")
        root.setProperty("--color0-model-error-connection", "#ffcccc")
        root.setProperty("--color1", "#b2f9fd")
        root.setProperty("--color2", "#009ba2")
        root.setProperty("--color2-model-success-connection", "#2ea200")
        root.setProperty("--color2-model-error-connection", "#a21800")
        root.setProperty("--color3", "#25c6ce")
        root.setProperty("--color3-model-success-connection", "#82ce25")
        root.setProperty("--color3-model-error-connection", "#ce2525")
        root.setProperty("--color4", "#20b6be")
        root.setProperty("--color4-model-success-node", "#30be20")
        root.setProperty("--color4-model-error-node", "#be3220")
        root.setProperty("--background0", "#e1e1e1")
        root.setProperty("--background1", "#b5bdc4")
        root.setProperty("--background2", "#62738c")
        root.setProperty("--background3", "#303744")
        root.setProperty("--background4", "#282828")
        root.setProperty("--border-color", "#000000")
        root.setProperty("--background-color", "#ffffff")
        root.setProperty("--background-box-title", "#d0d0d0")
        root.setProperty("--gradient-color", "#aebcd2")
        root.setProperty("--text-color", "#000000")
        root.setProperty("--notification-color-success", "#3fd778")
        root.setProperty("--notification-color-success-border", "#156532")
        root.setProperty("--notification-color-fail", "#f66262")
        root.setProperty("--notification-color-fail-border", "#913030")
    }
}
